# Generated by Django 5.2.4 on 2025-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
